/* GENERATED by scripts/gen-tokens.mjs from design/tokens.json. Do not edit. */
module.exports = {
  theme: {
    extend: {
      colors: {
        'sn-bg-base': 'var(--sn-bg-base)',
        'sn-bg-panel': 'var(--sn-bg-panel)',
        'sn-bg-sunken': 'var(--sn-bg-sunken)',
        'sn-line': 'var(--sn-line)',
        'sn-ink': 'var(--sn-ink)',
        'sn-ink-muted': 'var(--sn-ink-muted)',
        'sn-accent': 'var(--sn-accent)',
        'sn-attention': 'var(--sn-attention)',
        'sn-status-online': 'var(--sn-status-online)',
        'sn-status-error': 'var(--sn-status-error)',
      },
      boxShadow: {
        'sn-sm': 'var(--sn-shadow-sm)',
        'sn-md': 'var(--sn-shadow-md)',
      },
      borderRadius: {
        'sn-card': '20px',
        'sn-bubble': '14px',
        'sn-input': '999px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        data: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
        display: ['Syne', 'Inter', 'system-ui', 'sans-serif'],
      },
      transitionTimingFunction: { sn: 'cubic-bezier(.2,.8,.2,1)' },
      transitionDuration: {
        'sn-fast': '200ms',
        'sn-base': '250ms',
      },
    },
  },
};
