package com.guildofsmiths.trademesh.ui

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

/** GENERATED by scripts/gen-tokens.mjs from design/tokens.json. Do not edit. */
object Tokens2 {
    object Light {
        val BgBase = Color(0xFFF7F8FA)
        val BgPanel = Color(0xFFFFFFFF)
        val BgSunken = Color(0xFFEEF1F5)
        val Line = Color(0xFFE2E6EC)
        val Ink = Color(0xFF1C2128)
        val InkMuted = Color(0xFF7A8290)
        val Accent = Color(0xFF2F5FE8)
        val Attention = Color(0xFFE8590C)
        val StatusOnline = Color(0xFF3E9B4F)
        val StatusError = Color(0xFFD64545)
        val Overlay = Color(0x66000000)
        val InkOnAccent = Color(0xFFFFFFFF)
    }
    object Dark {
        val BgBase = Color(0xFF14171C)
        val BgPanel = Color(0xFF1D2129)
        val BgSunken = Color(0xFF0E1013)
        val Line = Color(0xFF2B303A)
        val Ink = Color(0xFFE9ECF1)
        val InkMuted = Color(0xFF8A93A3)
        val Accent = Color(0xFF6B8CFF)
        val Attention = Color(0xFFFF8A3D)
        val StatusOnline = Color(0xFF63C76F)
        val StatusError = Color(0xFFFF6B6B)
        val Overlay = Color(0x66000000)
        val InkOnAccent = Color(0xFFFFFFFF)
    }
    object Avatar {
        val A1 = Color(0xFF2F5FE8)
        val A2 = Color(0xFF3E9B4F)
        val A3 = Color(0xFF8A5FE8)
        val A4 = Color(0xFFE8590C)
        val A5 = Color(0xFF1F8A99)
        val A6 = Color(0xFFC2417E)
    }
    val AvatarPalette = listOf(Avatar.A1, Avatar.A2, Avatar.A3, Avatar.A4, Avatar.A5, Avatar.A6)
    val RadiusCard = 20.dp
    val RadiusBubble = 14.dp
    val RadiusOps = 0.dp
    const val DurationFastMs = 200
    const val DurationBaseMs = 250
}
