import { v4 as uuidv4 } from 'uuid';
import { Intent, IntentVersion, IntentStatus } from './types';
import { validateIntentCreation, validateIntentConfirmation, validateIntentVersion } from './intentAuthority';
import { pg, isPgEnabled } from './db';

function requirePg() {
  if (!isPgEnabled() || !pg) throw new Error('[IntentService] Postgres client not initialized');
  return pg;
}

export async function createIntent(
  scopeStatement: string,
  parties: string[],
  createdBy: string,
  intendedJobIds: string[] = []
): Promise<{ intent: Intent; version: IntentVersion } | { error: string }> {
  const db = requirePg();
  const validation = validateIntentCreation(scopeStatement, parties);
  if (!validation.valid) return { error: validation.message };

  const intentId = uuidv4();
  const versionId = uuidv4();
  const now = Date.now();

  const version: IntentVersion = {
    id: versionId, intentId, versionNumber: 1, status: 'draft',
    scopeStatement, intendedJobIds, parties, createdAt: now, autoGenerated: false,
  };
  const intent: Intent = {
    id: intentId, currentVersionId: versionId, createdBy, createdAt: now, updatedAt: now,
  };

  await db.query(
    `INSERT INTO intents (id, created_by, created_at, updated_at) VALUES ($1, $2, to_timestamp($3/1000.0), to_timestamp($3/1000.0))`,
    [intent.id, intent.createdBy, now]
  );

  await db.query(
    `INSERT INTO intent_versions
       (id, intent_id, version_number, status, scope_statement,
        intended_job_ids, parties, created_at, auto_generated)
     VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7::jsonb, to_timestamp($8/1000.0), $9)`,
    [
      version.id, version.intentId, version.versionNumber, version.status,
      version.scopeStatement, JSON.stringify(version.intendedJobIds),
      JSON.stringify(version.parties), now, version.autoGenerated,
    ]
  );

  await db.query(`UPDATE intents SET current_version_id = $1 WHERE id = $2`, [versionId, intentId]);
  return { intent, version };
}

export async function proposeIntent(versionId: string): Promise<IntentVersion | { error: string }> {
  const db = requirePg();
  const { rows } = await db.query(`SELECT * FROM intent_versions WHERE id = $1`, [versionId]);
  if (rows.length === 0) return { error: 'Intent version not found' };
  if (rows[0].status !== 'draft') return { error: 'Can only propose a draft Intent' };

  await db.query(`UPDATE intent_versions SET status = 'proposed' WHERE id = $1`, [versionId]);
  return { ...mapVersionRow(rows[0]), status: 'proposed' };
}

export async function confirmIntent(
  versionId: string, confirmerId: string
): Promise<IntentVersion | { error: string }> {
  const db = requirePg();
  const { rows } = await db.query(`SELECT * FROM intent_versions WHERE id = $1`, [versionId]);
  if (rows.length === 0) return { error: 'Intent version not found' };

  const version = mapVersionRow(rows[0]);
  const validation = validateIntentConfirmation(version, confirmerId);
  if (!validation.valid) return { error: validation.message };

  await db.query(
    `UPDATE intent_versions SET status = 'confirmed', confirmed_at = NOW(), confirmed_by = $1 WHERE id = $2`,
    [confirmerId, versionId]
  );

  return { ...version, status: 'confirmed', confirmedAt: Date.now(), confirmedBy: confirmerId };
}

export async function createNewVersion(
  intentId: string, priorVersionId: string, scopeStatement: string,
  parties: string[], intendedJobIds: string[], createdBy: string
): Promise<IntentVersion | { error: string }> {
  const db = requirePg();
  const { rows: priorRows } = await db.query(`SELECT * FROM intent_versions WHERE id = $1`, [priorVersionId]);
  if (priorRows.length === 0) return { error: 'Prior version not found' };

  const priorVersion = mapVersionRow(priorRows[0]);
  const newVersionId = uuidv4();
  const validation = validateIntentVersion({ supersedes: priorVersionId }, priorVersion);
  if (!validation.valid) return { error: validation.message };

  const now = Date.now();
  const newVersion: IntentVersion = {
    id: newVersionId, intentId, versionNumber: priorVersion.versionNumber + 1,
    status: 'draft', scopeStatement, intendedJobIds, parties,
    supersedes: priorVersionId, createdAt: now, autoGenerated: false,
  };

  await db.query(
    `UPDATE intent_versions SET status = 'superseded', superseded_by = $1 WHERE id = $2`,
    [newVersionId, priorVersionId]
  );

  await db.query(
    `INSERT INTO intent_versions
       (id, intent_id, version_number, status, scope_statement,
        intended_job_ids, parties, supersedes, created_at, auto_generated)
     VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7::jsonb, $8, to_timestamp($9/1000.0), $10)`,
    [
      newVersion.id, newVersion.intentId, newVersion.versionNumber, newVersion.status,
      newVersion.scopeStatement, JSON.stringify(newVersion.intendedJobIds),
      JSON.stringify(newVersion.parties), newVersion.supersedes, now, false,
    ]
  );

  await db.query(
    `UPDATE intents SET current_version_id = $1, updated_at = to_timestamp($2/1000.0) WHERE id = $3`,
    [newVersionId, now, intentId]
  );

  return newVersion;
}

export async function autoGenerateIntent(
  jobIds: string[], timeEntryIds: string[], actorUuid: string
): Promise<{ intent: Intent; version: IntentVersion } | { error: string }> {
  const db = requirePg();
  const scope = jobIds.length === 1
    ? `Completed single job (${jobIds[0].substring(0, 8)})`
    : `Completed ${jobIds.length} jobs`;

  const result = await createIntent(scope, [actorUuid], actorUuid, jobIds);
  if ('error' in result) return result;

  await db.query(
    `UPDATE intent_versions SET auto_generated = TRUE, status = 'proposed' WHERE id = $1`,
    [result.version.id]
  );

  result.version.autoGenerated = true;
  result.version.status = 'proposed';
  return result;
}

function mapVersionRow(row: any): IntentVersion {
  return {
    id: row.id, intentId: row.intent_id, versionNumber: row.version_number,
    status: row.status, scopeStatement: row.scope_statement,
    intendedJobIds: row.intended_job_ids || [], parties: row.parties || [],
    confirmedAt: row.confirmed_at ? new Date(row.confirmed_at).getTime() : undefined,
    confirmedBy: row.confirmed_by, supersededBy: row.superseded_by,
    supersedes: row.supersedes, createdAt: new Date(row.created_at).getTime(),
    autoGenerated: row.auto_generated,
  };
}
