import { v4 as uuidv4 } from 'uuid';
import { Intent, IntentVersion, IntentStatus } from './types';
import { validateIntentCreation, validateIntentConfirmation, validateIntentVersion } from './intentAuthority';
import { supabase } from './supabase';

export async function createIntent(
  scopeStatement: string,
  parties: string[],
  createdBy: string,
  intendedJobIds: string[] = []
): Promise<{ intent: Intent; version: IntentVersion } | { error: string }> {
  const validation = validateIntentCreation(scopeStatement, parties);
  if (!validation.valid) return { error: validation.message };

  const intentId = uuidv4();
  const versionId = uuidv4();
  const now = Date.now();

  const version: IntentVersion = {
    id: versionId, intentId, versionNumber: 1, status: 'draft',
    scopeStatement, intendedJobIds, parties, createdAt: now, autoGenerated: false,
  };

  const intent: Intent = {
    id: intentId, currentVersionId: versionId, createdBy, createdAt: now, updatedAt: now,
  };

  const { error: intentErr } = await supabase.from('intents').insert({
    id: intent.id, created_by: intent.createdBy,
    created_at: new Date(now).toISOString(), updated_at: new Date(now).toISOString(),
  });
  if (intentErr) return { error: intentErr.message };

  const { error: versionErr } = await supabase.from('intent_versions').insert({
    id: version.id, intent_id: version.intentId, version_number: version.versionNumber,
    status: version.status, scope_statement: version.scopeStatement,
    intended_job_ids: version.intendedJobIds, parties: version.parties,
    created_at: new Date(now).toISOString(), auto_generated: version.autoGenerated,
  });
  if (versionErr) return { error: versionErr.message };

  await supabase.from('intents').update({ current_version_id: versionId }).eq('id', intentId);
  return { intent, version };
}

export async function proposeIntent(versionId: string): Promise<IntentVersion | { error: string }> {
  const { data, error } = await supabase
    .from('intent_versions').select('*').eq('id', versionId).single();
  if (error || !data) return { error: 'Intent version not found' };
  if (data.status !== 'draft') return { error: 'Can only propose a draft Intent' };

  await supabase.from('intent_versions').update({ status: 'proposed' }).eq('id', versionId);
  return { ...mapVersionRow(data), status: 'proposed' };
}

export async function confirmIntent(
  versionId: string, confirmerId: string
): Promise<IntentVersion | { error: string }> {
  const { data, error } = await supabase
    .from('intent_versions').select('*').eq('id', versionId).single();
  if (error || !data) return { error: 'Intent version not found' };

  const version = mapVersionRow(data);
  const validation = validateIntentConfirmation(version, confirmerId);
  if (!validation.valid) return { error: validation.message };

  const now = new Date().toISOString();
  await supabase.from('intent_versions')
    .update({ status: 'confirmed', confirmed_at: now, confirmed_by: confirmerId })
    .eq('id', versionId);

  return { ...version, status: 'confirmed', confirmedAt: Date.now(), confirmedBy: confirmerId };
}

export async function createNewVersion(
  intentId: string, priorVersionId: string, scopeStatement: string,
  parties: string[], intendedJobIds: string[], createdBy: string
): Promise<IntentVersion | { error: string }> {
  const { data: priorData, error: priorErr } = await supabase
    .from('intent_versions').select('*').eq('id', priorVersionId).single();
  if (priorErr || !priorData) return { error: 'Prior version not found' };

  const priorVersion = mapVersionRow(priorData);
  const newVersionId = uuidv4();
  const validation = validateIntentVersion({ supersedes: priorVersionId }, priorVersion);
  if (!validation.valid) return { error: validation.message };

  const now = Date.now();
  const newVersion: IntentVersion = {
    id: newVersionId, intentId, versionNumber: priorVersion.versionNumber + 1,
    status: 'draft', scopeStatement, intendedJobIds, parties,
    supersedes: priorVersionId, createdAt: now, autoGenerated: false,
  };

  await supabase.from('intent_versions')
    .update({ status: 'superseded', superseded_by: newVersionId }).eq('id', priorVersionId);

  await supabase.from('intent_versions').insert({
    id: newVersion.id, intent_id: newVersion.intentId, version_number: newVersion.versionNumber,
    status: newVersion.status, scope_statement: newVersion.scopeStatement,
    intended_job_ids: newVersion.intendedJobIds, parties: newVersion.parties,
    supersedes: newVersion.supersedes, created_at: new Date(now).toISOString(), auto_generated: false,
  });

  await supabase.from('intents')
    .update({ current_version_id: newVersionId, updated_at: new Date(now).toISOString() })
    .eq('id', intentId);

  return newVersion;
}

export async function autoGenerateIntent(
  jobIds: string[], timeEntryIds: string[], actorUuid: string
): Promise<{ intent: Intent; version: IntentVersion } | { error: string }> {
  const scope = jobIds.length === 1
    ? `Completed single job (${jobIds[0].substring(0, 8)})`
    : `Completed ${jobIds.length} jobs`;

  const result = await createIntent(scope, [actorUuid], actorUuid, jobIds);
  if ('error' in result) return result;

  await supabase.from('intent_versions')
    .update({ auto_generated: true, status: 'proposed' }).eq('id', result.version.id);

  result.version.autoGenerated = true;
  result.version.status = 'proposed';
  return result;
}

function mapVersionRow(row: any): IntentVersion {
  return {
    id: row.id, intentId: row.intent_id, versionNumber: row.version_number,
    status: row.status, scopeStatement: row.scope_statement,
    intendedJobIds: row.intended_job_ids || [], parties: row.parties || [],
    confirmedAt: row.confirmed_at ? new Date(row.confirmed_at).getTime() : undefined,
    confirmedBy: row.confirmed_by, supersededBy: row.superseded_by,
    supersedes: row.supersedes, createdAt: new Date(row.created_at).getTime(),
    autoGenerated: row.auto_generated,
  };
}
