/**
 * PAYROLL DOCUMENTS — Feature #26 from gosv2.txt
 * ==============================================
 *
 * Generate paystubs and printable checks for payroll
 * Especially important for enterprise/crew operations
 */

import { TimeEntry } from './types';

export interface PayrollData {
  // Employee
  employeeId: string;
  employeeName: string;
  employeeAddress: string;
  employeeSsn?: string; // Last 4 digits only for display
  
  // Employer
  employerName: string;
  employerAddress: string;
  employerEin?: string;

  // Pay period
  payPeriodStart: string;
  payPeriodEnd: string;
  payDate: string;
  checkNumber?: string;

  // Hours and earnings
  regularHours: number;
  overtimeHours: number;
  doubleTimeHours: number;
  regularRate: number;
  overtimeRate: number;
  doubleTimeRate: number;

  // Gross pay
  regularPay: number;
  overtimePay: number;
  doubleTimePay: number;
  bonuses: number;
  grossPay: number;

  // Deductions
  federalTax: number;
  stateTax: number;
  socialSecurity: number;
  medicare: number;
  otherDeductions: Array<{
    name: string;
    amount: number;
  }>;
  totalDeductions: number;

  // Net pay
  netPay: number;

  // Year-to-date
  ytdGross?: number;
  ytdDeductions?: number;
  ytdNet?: number;
}

export class PayrollDocuments {

  /**
   * Generate paystub
   */
  generatePaystub(data: PayrollData): string {
    const otherDeductionsLines = data.otherDeductions.map(d =>
      `${d.name.padEnd(30)} $${d.amount.toFixed(2).padStart(10)}`
    ).join('\n');

    return `══════════════════════════════════════════════════════════════════
                          PAYROLL STATEMENT
══════════════════════════════════════════════════════════════════

Employer: ${data.employerName}
          ${data.employerAddress}
          ${data.employerEin ? `EIN: ${data.employerEin}` : ''}

Employee: ${data.employeeName}
          ${data.employeeAddress}
          ${data.employeeSsn ? `SSN: ***-**-${data.employeeSsn}` : ''}

Pay Period: ${data.payPeriodStart} to ${data.payPeriodEnd}
Pay Date:   ${data.payDate}
Check #:    ${data.checkNumber || 'N/A'}

──────────────────────────────────────────────────────────────────
EARNINGS                          Hours    Rate      Amount
──────────────────────────────────────────────────────────────────
Regular Pay                      ${String(data.regularHours).padStart(6)}  $${data.regularRate.toFixed(2).padStart(6)}  $${data.regularPay.toFixed(2).padStart(10)}
Overtime Pay (1.5x)              ${String(data.overtimeHours).padStart(6)}  $${data.overtimeRate.toFixed(2).padStart(6)}  $${data.overtimePay.toFixed(2).padStart(10)}
${data.doubleTimeHours > 0 ? `Double Time Pay (2x)             ${String(data.doubleTimeHours).padStart(6)}  $${data.doubleTimeRate.toFixed(2).padStart(6)}  $${data.doubleTimePay.toFixed(2).padStart(10)}` : ''}
${data.bonuses > 0 ? `Bonuses                                                   $${data.bonuses.toFixed(2).padStart(10)}` : ''}
──────────────────────────────────────────────────────────────────
GROSS PAY                                                 $${data.grossPay.toFixed(2).padStart(10)}

──────────────────────────────────────────────────────────────────
DEDUCTIONS
──────────────────────────────────────────────────────────────────
Federal Income Tax                                        $${data.federalTax.toFixed(2).padStart(10)}
State Income Tax                                          $${data.stateTax.toFixed(2).padStart(10)}
Social Security (6.2%)                                    $${data.socialSecurity.toFixed(2).padStart(10)}
Medicare (1.45%)                                          $${data.medicare.toFixed(2).padStart(10)}
${otherDeductionsLines}
──────────────────────────────────────────────────────────────────
TOTAL DEDUCTIONS                                          $${data.totalDeductions.toFixed(2).padStart(10)}

══════════════════════════════════════════════════════════════════
NET PAY                                                   $${data.netPay.toFixed(2).padStart(10)}
══════════════════════════════════════════════════════════════════

${data.ytdGross ? `
YEAR-TO-DATE SUMMARY (as of ${data.payDate})
──────────────────────────────────────────────────────────────────
YTD Gross Pay                                             $${data.ytdGross.toFixed(2).padStart(10)}
YTD Deductions                                            $${data.ytdDeductions!.toFixed(2).padStart(10)}
YTD Net Pay                                               $${data.ytdNet!.toFixed(2).padStart(10)}
` : ''}

Generated by Smith Net Payroll System
This is not a check. For actual payment, see attached check or direct deposit confirmation.
══════════════════════════════════════════════════════════════════
`;
  }

  /**
   * Generate printable check
   */
  generateCheck(data: PayrollData): string {
    const payToOrderLine = `${data.netPay.toFixed(2)}`;
    const amountInWords = this.numberToWords(data.netPay);

    return `
┌────────────────────────────────────────────────────────────────┐
│                                                                │
│  ${data.employerName.padEnd(60)}│
│  ${data.employerAddress.padEnd(60)}│
│                                                     ${data.checkNumber || '0000'}│
│                                                                │
│  Date: ${data.payDate.padEnd(51)}│
│                                                                │
│  Pay to the                                                    │
│  Order of: ${data.employeeName.padEnd(48)}│
│                                                                │
│            $ ${payToOrderLine.padStart(10)}                                     │
│                                                                │
│  ${amountInWords.padEnd(62)}│
│  ──────────────────────────────────────────────────────── Dollars│
│                                                                │
│  Memo: Pay Period ${data.payPeriodStart} - ${data.payPeriodEnd.padEnd(26)}│
│                                                                │
│                                                                │
│                              _______________________________   │
│                              Authorized Signature              │
│                                                                │
└────────────────────────────────────────────────────────────────┘

                      *** DETACH HERE ***

┌────────────────────────────────────────────────────────────────┐
│ CHECK STUB — RETAIN FOR YOUR RECORDS                           │
├────────────────────────────────────────────────────────────────┤
│ Employee: ${data.employeeName.padEnd(50)}│
│ Check #:  ${(data.checkNumber || 'N/A').padEnd(50)}│
│ Pay Date: ${data.payDate.padEnd(50)}│
│                                                                │
│ Gross Pay:         $${data.grossPay.toFixed(2).padStart(10)}                              │
│ Total Deductions:  $${data.totalDeductions.toFixed(2).padStart(10)}                              │
│ NET PAY:           $${data.netPay.toFixed(2).padStart(10)}                              │
│                                                                │
│ Regular Hours: ${String(data.regularHours).padStart(6)}   Overtime: ${String(data.overtimeHours).padStart(6)}           │
└────────────────────────────────────────────────────────────────┘
`;
  }

  /**
   * Calculate payroll from time entries
   */
  calculatePayroll(
    timeEntries: TimeEntry[],
    regularRate: number,
    payPeriodStart: string,
    payPeriodEnd: string
  ): {
    regularHours: number;
    overtimeHours: number;
    doubleTimeHours: number;
    regularPay: number;
    overtimePay: number;
    doubleTimePay: number;
    grossPay: number;
  } {
    let totalMinutes = 0;

    // Sum all time entries in pay period
    for (const entry of timeEntries) {
      if (entry.clockOutTime && entry.durationMinutes) {
        totalMinutes += entry.durationMinutes;
      }
    }

    const totalHours = totalMinutes / 60;

    // Calculate overtime (over 40 hours/week)
    // For simplicity, assume all hours over 40 are overtime
    // Real implementation would need weekly breakdown
    const regularHours = Math.min(totalHours, 40);
    const overtimeHours = totalHours > 40 ? Math.min(totalHours - 40, 40) : 0;
    const doubleTimeHours = totalHours > 80 ? totalHours - 80 : 0;

    const overtimeRate = regularRate * 1.5;
    const doubleTimeRate = regularRate * 2.0;

    const regularPay = regularHours * regularRate;
    const overtimePay = overtimeHours * overtimeRate;
    const doubleTimePay = doubleTimeHours * doubleTimeRate;
    const grossPay = regularPay + overtimePay + doubleTimePay;

    return {
      regularHours: Math.round(regularHours * 100) / 100,
      overtimeHours: Math.round(overtimeHours * 100) / 100,
      doubleTimeHours: Math.round(doubleTimeHours * 100) / 100,
      regularPay: Math.round(regularPay * 100) / 100,
      overtimePay: Math.round(overtimePay * 100) / 100,
      doubleTimePay: Math.round(doubleTimePay * 100) / 100,
      grossPay: Math.round(grossPay * 100) / 100
    };
  }

  /**
   * Calculate standard deductions (simplified - real implementation needs tax tables)
   */
  calculateDeductions(grossPay: number, filingStatus: 'single' | 'married' = 'single'): {
    federalTax: number;
    stateTax: number;
    socialSecurity: number;
    medicare: number;
    totalDeductions: number;
  } {
    // Federal tax (very simplified - should use IRS tax tables)
    const federalTaxRate = filingStatus === 'single' ? 0.12 : 0.10;
    const federalTax = grossPay * federalTaxRate;

    // State tax (assume 5% average)
    const stateTax = grossPay * 0.05;

    // Social Security (6.2% up to wage base)
    const socialSecurity = grossPay * 0.062;

    // Medicare (1.45%)
    const medicare = grossPay * 0.0145;

    const totalDeductions = federalTax + stateTax + socialSecurity + medicare;

    return {
      federalTax: Math.round(federalTax * 100) / 100,
      stateTax: Math.round(stateTax * 100) / 100,
      socialSecurity: Math.round(socialSecurity * 100) / 100,
      medicare: Math.round(medicare * 100) / 100,
      totalDeductions: Math.round(totalDeductions * 100) / 100
    };
  }

  /**
   * Convert number to words for check writing
   */
  private numberToWords(num: number): string {
    const ones = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine'];
    const teens = ['Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'];
    const tens = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];

    const dollars = Math.floor(num);
    const cents = Math.round((num - dollars) * 100);

    let words = '';

    if (dollars >= 1000) {
      const thousands = Math.floor(dollars / 1000);
      words += this.convertHundreds(thousands) + ' Thousand ';
      const remainder = dollars % 1000;
      if (remainder > 0) {
        words += this.convertHundreds(remainder) + ' ';
      }
    } else {
      words += this.convertHundreds(dollars) + ' ';
    }

    words += 'and ' + String(cents).padStart(2, '0') + '/100';
    return words;
  }

  private convertHundreds(num: number): string {
    const ones = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine'];
    const teens = ['Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'];
    const tens = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];

    let words = '';
    
    if (num >= 100) {
      words += ones[Math.floor(num / 100)] + ' Hundred ';
      num %= 100;
    }
    
    if (num >= 20) {
      words += tens[Math.floor(num / 10)] + ' ';
      num %= 10;
    } else if (num >= 10) {
      words += teens[num - 10] + ' ';
      return words;
    }
    
    if (num > 0) {
      words += ones[num] + ' ';
    }
    
    return words.trim();
  }
}

export const payrollDocuments = new PayrollDocuments();
