package com.guildofsmiths.trademesh.data

import android.content.SharedPreferences
import com.guildofsmiths.trademesh.ui.plan.*
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import org.json.JSONArray
import org.json.JSONObject
import java.util.UUID

object IntentRepository {
    private val _intents = MutableStateFlow<List<IntentData>>(emptyList())
    val intents: StateFlow<List<IntentData>> = _intents

    private val _versions = MutableStateFlow<List<IntentVersionData>>(emptyList())
    val versions: StateFlow<List<IntentVersionData>> = _versions

    private var serialCounter = 0
    private var prefs: SharedPreferences? = null

    // Pending intent for job creation — set when user taps "CREATE JOB" from confirmed intent
    private val _pendingIntentForJob = MutableStateFlow<IntentVersionData?>(null)
    val pendingIntentForJob: StateFlow<IntentVersionData?> = _pendingIntentForJob

    fun setPendingIntentForJob(version: IntentVersionData?) {
        _pendingIntentForJob.value = version
    }

    fun clearPendingIntentForJob() {
        _pendingIntentForJob.value = null
    }

    fun init(prefs: SharedPreferences) {
        this.prefs = prefs
        serialCounter = prefs.getInt("intent_serial_counter", 0)
        restorePersisted()
    }

    fun createIntent(
        scopeStatement: String,
        parties: List<String>,
        createdBy: String,
        intendedJobIds: List<String> = emptyList(),
        taskDescriptions: List<String> = emptyList(),
        equipmentNeeded: List<String> = emptyList(),
        suppliesNeeded: List<String> = emptyList(),
        crewSize: Int = 1
    ): Pair<IntentData, IntentVersionData> {
        val now = System.currentTimeMillis()
        val intentId = "intent_${now}_${(0..999).random()}"
        val versionId = UUID.randomUUID().toString()

        val version = IntentVersionData(
            id = versionId, intentId = intentId, versionNumber = 1,
            status = IntentStatus.DRAFT, scopeStatement = scopeStatement,
            intendedJobIds = intendedJobIds, parties = parties,
            taskDescriptions = taskDescriptions,
            equipmentNeeded = equipmentNeeded,
            suppliesNeeded = suppliesNeeded,
            crewSize = crewSize,
            createdAt = now, autoGenerated = false
        )

        val intent = IntentData(
            id = intentId, currentVersionId = versionId,
            createdBy = createdBy, createdAt = now, updatedAt = now
        )

        _intents.value = listOf(intent) + _intents.value
        _versions.value = listOf(version) + _versions.value
        persist()
        return Pair(intent, version)
    }

    fun proposeVersion(versionId: String): Boolean {
        val updated = _versions.value.map {
            if (it.id == versionId && it.status == IntentStatus.DRAFT)
                it.copy(status = IntentStatus.PROPOSED) else it
        }
        _versions.value = updated
        val ok = updated.any { it.id == versionId && it.status == IntentStatus.PROPOSED }
        if (ok) persist()
        return ok
    }

    fun confirmVersion(versionId: String, confirmerId: String): Boolean {
        val now = System.currentTimeMillis()
        val updated = _versions.value.map {
            if (it.id == versionId && it.status == IntentStatus.PROPOSED)
                it.copy(status = IntentStatus.CONFIRMED, confirmedAt = now, confirmedBy = confirmerId) else it
        }
        _versions.value = updated
        val ok = updated.any { it.id == versionId && it.status == IntentStatus.CONFIRMED }
        if (ok) persist()
        return ok
    }

    fun createNewVersion(
        intentId: String, priorVersionId: String, scopeStatement: String,
        parties: List<String>, intendedJobIds: List<String>,
        taskDescriptions: List<String> = emptyList(),
        equipmentNeeded: List<String> = emptyList(),
        suppliesNeeded: List<String> = emptyList(),
        crewSize: Int = 1
    ): IntentVersionData? {
        val prior = _versions.value.find { it.id == priorVersionId } ?: return null
        if (prior.status == IntentStatus.SUPERSEDED) return null

        val now = System.currentTimeMillis()
        val newVersionId = UUID.randomUUID().toString()

        val newVersion = IntentVersionData(
            id = newVersionId, intentId = intentId,
            versionNumber = prior.versionNumber + 1,
            status = IntentStatus.DRAFT, scopeStatement = scopeStatement,
            intendedJobIds = intendedJobIds, parties = parties,
            taskDescriptions = taskDescriptions,
            equipmentNeeded = equipmentNeeded,
            suppliesNeeded = suppliesNeeded,
            crewSize = crewSize,
            supersedes = priorVersionId, createdAt = now, autoGenerated = false
        )

        _versions.value = _versions.value.map {
            if (it.id == priorVersionId) it.copy(status = IntentStatus.SUPERSEDED, supersededBy = newVersionId)
            else it
        } + newVersion

        _intents.value = _intents.value.map {
            if (it.id == intentId) it.copy(currentVersionId = newVersionId, updatedAt = now)
            else it
        }

        persist()
        return newVersion
    }

    fun getVersionsForIntent(intentId: String): List<IntentVersionData> {
        return _versions.value.filter { it.intentId == intentId }.sortedByDescending { it.versionNumber }
    }

    fun getCurrentVersion(intentId: String): IntentVersionData? {
        val intent = _intents.value.find { it.id == intentId } ?: return null
        return _versions.value.find { it.id == intent.currentVersionId }
    }

    fun generateSerial(): String {
        serialCounter++
        prefs?.edit()?.putInt("intent_serial_counter", serialCounter)?.apply()
        val year = java.util.Calendar.getInstance().get(java.util.Calendar.YEAR)
        return "INT-$year-${String.format("%03d", serialCounter)}"
    }

    // ════════════════════════════════════════════════════════════════════
    // PERSISTENCE
    // ════════════════════════════════════════════════════════════════════

    private fun persist() {
        UserPreferences.saveIntents(intentsToJson(_intents.value).toString())
        UserPreferences.saveIntentVersions(versionsToJson(_versions.value).toString())
    }

    private fun restorePersisted() {
        val intentsJson = UserPreferences.getIntents()
        if (intentsJson != null) {
            try {
                val arr = JSONArray(intentsJson)
                val list = mutableListOf<IntentData>()
                for (i in 0 until arr.length()) list += parseIntent(arr.getJSONObject(i))
                if (list.isNotEmpty()) {
                    _intents.value = list
                }
            } catch (e: Exception) {
                android.util.Log.w("IntentRepo", "restore intents failed", e)
            }
        }
        val versionsJson = UserPreferences.getIntentVersions()
        if (versionsJson != null) {
            try {
                val arr = JSONArray(versionsJson)
                val list = mutableListOf<IntentVersionData>()
                for (i in 0 until arr.length()) list += parseVersion(arr.getJSONObject(i))
                if (list.isNotEmpty()) {
                    _versions.value = list
                }
            } catch (e: Exception) {
                android.util.Log.w("IntentRepo", "restore versions failed", e)
            }
        }
    }

    private fun intentsToJson(intents: List<IntentData>): JSONArray {
        val arr = JSONArray()
        intents.forEach {
            arr.put(JSONObject().apply {
                put("id", it.id)
                put("currentVersionId", it.currentVersionId)
                put("createdBy", it.createdBy)
                put("createdAt", it.createdAt)
                put("updatedAt", it.updatedAt)
            })
        }
        return arr
    }

    private fun parseIntent(json: JSONObject): IntentData = IntentData(
        id = json.getString("id"),
        currentVersionId = json.getString("currentVersionId"),
        createdBy = json.optString("createdBy", ""),
        createdAt = json.optLong("createdAt", 0L),
        updatedAt = json.optLong("updatedAt", 0L)
    )

    private fun versionsToJson(versions: List<IntentVersionData>): JSONArray {
        val arr = JSONArray()
        versions.forEach { v ->
            arr.put(JSONObject().apply {
                put("id", v.id)
                put("intentId", v.intentId)
                put("versionNumber", v.versionNumber)
                put("status", v.status.name)
                put("scopeStatement", v.scopeStatement)
                put("intendedJobIds", JSONArray().also { a -> v.intendedJobIds.forEach { a.put(it) } })
                put("parties", JSONArray().also { a -> v.parties.forEach { a.put(it) } })
                put("taskDescriptions", JSONArray().also { a -> v.taskDescriptions.forEach { a.put(it) } })
                put("equipmentNeeded", JSONArray().also { a -> v.equipmentNeeded.forEach { a.put(it) } })
                put("suppliesNeeded", JSONArray().also { a -> v.suppliesNeeded.forEach { a.put(it) } })
                put("crewSize", v.crewSize)
                if (v.confirmedAt != null) put("confirmedAt", v.confirmedAt)
                if (v.confirmedBy != null) put("confirmedBy", v.confirmedBy)
                if (v.supersededBy != null) put("supersededBy", v.supersededBy)
                if (v.supersedes != null) put("supersedes", v.supersedes)
                put("createdAt", v.createdAt)
                put("autoGenerated", v.autoGenerated)
            })
        }
        return arr
    }

    private fun parseVersion(json: JSONObject): IntentVersionData {
        fun stringList(key: String): List<String> {
            val a = json.optJSONArray(key) ?: return emptyList()
            return (0 until a.length()).map { a.getString(it) }
        }
        return IntentVersionData(
            id = json.getString("id"),
            intentId = json.getString("intentId"),
            versionNumber = json.optInt("versionNumber", 1),
            status = runCatching { IntentStatus.valueOf(json.optString("status", "DRAFT")) }
                .getOrDefault(IntentStatus.DRAFT),
            scopeStatement = json.optString("scopeStatement", ""),
            intendedJobIds = stringList("intendedJobIds"),
            parties = stringList("parties"),
            taskDescriptions = stringList("taskDescriptions"),
            equipmentNeeded = stringList("equipmentNeeded"),
            suppliesNeeded = stringList("suppliesNeeded"),
            crewSize = json.optInt("crewSize", 1),
            confirmedAt = if (json.has("confirmedAt")) json.getLong("confirmedAt") else null,
            confirmedBy = if (json.has("confirmedBy")) json.getString("confirmedBy") else null,
            supersededBy = if (json.has("supersededBy")) json.getString("supersededBy") else null,
            supersedes = if (json.has("supersedes")) json.getString("supersedes") else null,
            createdAt = json.optLong("createdAt", 0L),
            autoGenerated = json.optBoolean("autoGenerated", false)
        )
    }
}
