package com.guildofsmiths.trademesh.data

import android.content.SharedPreferences
import com.guildofsmiths.trademesh.ui.plan.*
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import java.util.UUID

object IntentRepository {
    private val _intents = MutableStateFlow<List<IntentData>>(emptyList())
    val intents: StateFlow<List<IntentData>> = _intents

    private val _versions = MutableStateFlow<List<IntentVersionData>>(emptyList())
    val versions: StateFlow<List<IntentVersionData>> = _versions

    private var serialCounter = 0
    private var prefs: SharedPreferences? = null

    fun init(prefs: SharedPreferences) {
        this.prefs = prefs
        serialCounter = prefs.getInt("intent_serial_counter", 0)
    }

    fun createIntent(
        scopeStatement: String, parties: List<String>, createdBy: String,
        intendedJobIds: List<String> = emptyList()
    ): Pair<IntentData, IntentVersionData> {
        val now = System.currentTimeMillis()
        val intentId = "intent_${now}_${(0..999).random()}"
        val versionId = UUID.randomUUID().toString()

        val version = IntentVersionData(
            id = versionId, intentId = intentId, versionNumber = 1,
            status = IntentStatus.DRAFT, scopeStatement = scopeStatement,
            intendedJobIds = intendedJobIds, parties = parties,
            createdAt = now, autoGenerated = false
        )

        val intent = IntentData(
            id = intentId, currentVersionId = versionId,
            createdBy = createdBy, createdAt = now, updatedAt = now
        )

        _intents.value = listOf(intent) + _intents.value
        _versions.value = listOf(version) + _versions.value
        return Pair(intent, version)
    }

    fun proposeVersion(versionId: String): Boolean {
        val updated = _versions.value.map {
            if (it.id == versionId && it.status == IntentStatus.DRAFT)
                it.copy(status = IntentStatus.PROPOSED) else it
        }
        _versions.value = updated
        return updated.any { it.id == versionId && it.status == IntentStatus.PROPOSED }
    }

    fun confirmVersion(versionId: String, confirmerId: String): Boolean {
        val now = System.currentTimeMillis()
        val updated = _versions.value.map {
            if (it.id == versionId && it.status == IntentStatus.PROPOSED)
                it.copy(status = IntentStatus.CONFIRMED, confirmedAt = now, confirmedBy = confirmerId) else it
        }
        _versions.value = updated
        return updated.any { it.id == versionId && it.status == IntentStatus.CONFIRMED }
    }

    fun createNewVersion(
        intentId: String, priorVersionId: String, scopeStatement: String,
        parties: List<String>, intendedJobIds: List<String>
    ): IntentVersionData? {
        val prior = _versions.value.find { it.id == priorVersionId } ?: return null
        if (prior.status == IntentStatus.SUPERSEDED) return null

        val now = System.currentTimeMillis()
        val newVersionId = UUID.randomUUID().toString()

        val newVersion = IntentVersionData(
            id = newVersionId, intentId = intentId,
            versionNumber = prior.versionNumber + 1,
            status = IntentStatus.DRAFT, scopeStatement = scopeStatement,
            intendedJobIds = intendedJobIds, parties = parties,
            supersedes = priorVersionId, createdAt = now, autoGenerated = false
        )

        _versions.value = _versions.value.map {
            if (it.id == priorVersionId) it.copy(status = IntentStatus.SUPERSEDED, supersededBy = newVersionId)
            else it
        } + newVersion

        _intents.value = _intents.value.map {
            if (it.id == intentId) it.copy(currentVersionId = newVersionId, updatedAt = now)
            else it
        }

        return newVersion
    }

    fun getVersionsForIntent(intentId: String): List<IntentVersionData> {
        return _versions.value.filter { it.intentId == intentId }.sortedByDescending { it.versionNumber }
    }

    fun getCurrentVersion(intentId: String): IntentVersionData? {
        val intent = _intents.value.find { it.id == intentId } ?: return null
        return _versions.value.find { it.id == intent.currentVersionId }
    }

    fun generateSerial(): String {
        serialCounter++
        prefs?.edit()?.putInt("intent_serial_counter", serialCounter)?.apply()
        val year = java.util.Calendar.getInstance().get(java.util.Calendar.YEAR)
        return "INT-$year-${String.format("%03d", serialCounter)}"
    }
}
