#!/usr/bin/env node
// Generates portal CSS vars + Tailwind preset and Android Tokens2.kt from
// design/tokens.json. --check exits 1 when outputs are stale.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const t = JSON.parse(readFileSync(resolve(root, 'design/tokens.json'), 'utf8'));
const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const upper = (s) => s[0].toUpperCase() + s.slice(1);

function cssVars(theme, pad = '  ') {
  const lines = Object.entries(t.color[theme]).map(([k, v]) => `${pad}--sn-${kebab(k)}: ${v};`);
  lines.push(`${pad}--sn-shadow-sm: ${t.shadow[theme].sm};`);
  lines.push(`${pad}--sn-shadow-md: ${t.shadow[theme].md};`);
  return lines.join('\n');
}

const css = `/* GENERATED by scripts/gen-tokens.mjs from design/tokens.json. Do not edit. */
:root {
${cssVars('light')}
  --sn-ease: ${t.motion.easing};
  --sn-dur-fast: ${t.motion.durationFastMs}ms;
  --sn-dur-base: ${t.motion.durationBaseMs}ms;
}
:root[data-theme="dark"] {
${cssVars('dark')}
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${cssVars('dark', '    ')}
  }
}
`;

const colorKeys = Object.keys(t.color.light);
const preset = `/* GENERATED by scripts/gen-tokens.mjs from design/tokens.json. Do not edit. */
module.exports = {
  theme: {
    extend: {
      colors: {
${colorKeys.map((k) => `        'sn-${kebab(k)}': 'var(--sn-${kebab(k)})',`).join('\n')}
      },
      boxShadow: {
        'sn-sm': 'var(--sn-shadow-sm)',
        'sn-md': 'var(--sn-shadow-md)',
      },
      borderRadius: {
        'sn-card': '${t.radius.card}px',
        'sn-bubble': '${t.radius.bubble}px',
        'sn-input': '${t.radius.input}px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        data: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
        display: ['Syne', 'Inter', 'system-ui', 'sans-serif'],
      },
      transitionTimingFunction: { sn: '${t.motion.easing}' },
      transitionDuration: {
        'sn-fast': '${t.motion.durationFastMs}ms',
        'sn-base': '${t.motion.durationBaseMs}ms',
      },
    },
  },
};
`;

const ktColor = (hex) => `Color(0xFF${hex.slice(1).toUpperCase()})`;
const ktObj = (theme) =>
  Object.entries(t.color[theme]).map(([k, v]) => `        val ${upper(k)} = ${ktColor(v)}`).join('\n');
const kt = `package com.guildofsmiths.trademesh.ui

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

/** GENERATED by scripts/gen-tokens.mjs from design/tokens.json. Do not edit. */
object Tokens2 {
    object Light {
${ktObj('light')}
    }
    object Dark {
${ktObj('dark')}
    }
    val RadiusCard = ${t.radius.card}.dp
    val RadiusBubble = ${t.radius.bubble}.dp
    val RadiusOps = ${t.radius.ops}.dp
    const val DurationFastMs = ${t.motion.durationFastMs}
    const val DurationBaseMs = ${t.motion.durationBaseMs}
}
`;

const outputs = [
  ['desktop/portal/src/styles/tokens.css', css],
  ['desktop/portal/tailwind.tokens.cjs', preset],
  ['android/app/src/main/java/com/guildofsmiths/trademesh/ui/Tokens2.kt', kt],
];

const check = process.argv.includes('--check');
let stale = false;
for (const [rel, content] of outputs) {
  const abs = resolve(root, rel);
  if (check) {
    const current = existsSync(abs) ? readFileSync(abs, 'utf8') : '';
    if (current !== content) { console.error(`[stale] ${rel}`); stale = true; }
  } else {
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, content);
    console.log(`[wrote] ${rel}`);
  }
}
if (check && stale) { console.error('Run: node scripts/gen-tokens.mjs'); process.exit(1); }
if (check) console.log('tokens up to date');
