package com.guildofsmiths.trademesh.ui.plan

enum class IntentStatus(val displayName: String, val icon: String) {
    DRAFT("Draft", "[◫]"),
    PROPOSED("Proposed", "[⊞]"),
    CONFIRMED("Confirmed", "[✓]"),
    SUPERSEDED("Superseded", "[↻]")
}

data class IntentData(
    val id: String,
    val currentVersionId: String,
    val createdBy: String,
    val createdAt: Long,
    val updatedAt: Long
)

data class IntentVersionData(
    val id: String,
    val intentId: String,
    val versionNumber: Int,
    val status: IntentStatus = IntentStatus.DRAFT,
    val scopeStatement: String,
    val intendedJobIds: List<String> = emptyList(),
    val parties: List<String> = emptyList(),
    val confirmedAt: Long? = null,
    val confirmedBy: String? = null,
    val supersededBy: String? = null,
    val supersedes: String? = null,
    val createdAt: Long,
    val autoGenerated: Boolean = false
) {
    fun canPropose(): Boolean = status == IntentStatus.DRAFT && scopeStatement.isNotBlank()
    fun canConfirm(): Boolean = status == IntentStatus.PROPOSED
    fun isEditable(): Boolean = status == IntentStatus.DRAFT
}

data class SummaryArtifactData(
    val id: String,
    val serial: String,
    val intentVersionId: String,
    val scopeStatement: String,
    val workPerformed: List<String> = emptyList(),
    val laborRecorded: List<String> = emptyList(),
    val materialsUsed: List<String> = emptyList(),
    val contextualNotes: List<String> = emptyList(),
    val totalHours: Double,
    val totalCost: Double,
    val jobIds: List<String> = emptyList(),
    val timeEntryIds: List<String> = emptyList(),
    val createdAt: Long
)

data class LedgerEntryData(
    val id: String,
    val artifactSerial: String,
    val artifactId: String,
    val sha256Hash: String,
    val actorUuid: String,
    val supersedes: String? = null,
    val supersededBy: String? = null,
    val sealedAt: Long
)

enum class IntentFilter {
    ALL,
    ACTIVE,
    CONFIRMED,
    SUPERSEDED
}
